services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=${PORT:-3000}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - API_BASE_URL=${API_BASE_URL:-https://answers.mindenit.org/api}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
